#cloud-config

write_files:
 -  content: |
        [Service]
        ExecStart=
        ExecStart=/usr/bin/dockerd -H unix:///var/run/docker.sock -H 0.0.0.0:2375
    path: /etc/systemd/system/docker.service.d/docker.conf
    permissions: '0444'
 -  content: |
        #!/bin/bash

        DOCKER_COMPOSE_VERSION="1.8.1"
        MASTER0HOSTNAME=${1}
        AZUREUSER=${2}

        echo "$(hostname -i) $(hostname)" | sudo tee -a /etc/hosts

        echo "Installing and configuring docker"

        installDocker()
        {
            for i in {1..10}; do
                wget --tries 4 --retry-connrefused --waitretry=15 -qO- https://get.docker.com | sh
                if [ $? -eq 0 ]
                then
                    # hostname has been found continue
                    echo "Docker installed successfully"
                    break
                fi
                sleep 10
            done
        }
        time installDocker
        sudo usermod -aG docker $AZUREUSER

        sudo systemctl daemon-reload
        sudo service docker restart

        echo "Installing docker compose"
        installDockerCompose()
        {
            for i in {1..10}; do
                wget --tries 4 --retry-connrefused --waitretry=15 -qO- https://github.com/docker/compose/releases/download/$DOCKER_COMPOSE_VERSION/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
                if [ $? -eq 0 ]
                then
                    # hostname has been found continue
                    echo "docker-compose installed successfully"
                    break
                fi
                sleep 10
            done
        }
        time installDockerCompose
        chmod +x /usr/local/bin/docker-compose

        ensureDocker()
        {
            # ensure that docker is healthy
            dockerHealthy=1
            for i in {1..3}; do
                sudo docker info
                if [ $? -eq 0 ]
                then
                    # hostname has been found continue
                    dockerHealthy=0
                    echo "Docker is healthy"
                    sudo docker ps -a
                    break
                fi
                sleep 10
            done
            if [ $dockerHealthy -ne 0 ]
            then
                echo "Docker is not healthy"
            fi
        }
        ensureDocker

        echo "this node is a master"
        if [ "$(hostname)" = "$MASTER0HOSTNAME" ]; then
            echo "this is the first master, creating swarm"
            docker swarm init --advertise-addr $(hostname -i):2377 --listen-addr $(hostname -i):2377
        else
            echo "this is a secondary master"
            swarmkey=""
            hasswarmkey=1
            for i in {1..120}; do
                swarmkey=$(docker -H $(dig +short +search $MASTER0HOSTNAME):2375 swarm join-token manager -q)
                if [ $? -eq 0 ]; then
                    hasswarmkey=0
                    break;
                fi 
            done
            if [ $hasswarmkey -ne 0 ]
            then
                echo "couldn't connect to swarm, aborting."
                exit 2
            fi
            docker swarm join --token $swarmkey $(dig +short +search $MASTER0HOSTNAME):2377
        fi
        echo "completed swarm configuration"
    path: /opt/azure/containers/configure-swarm-cluster.sh
    permissions: '0744'
 -  content: |
        #!/bin/bash
        sudo mkdir /var/log/azure
        /usr/bin/nohup sudo /bin/bash -c "/bin/bash /opt/azure/containers/configure-swarm-cluster.sh swarm-master-1 clustermanager > /var/log/azure/cluster-bootstrap.log 2>&1 &" &
        
    path: /opt/azure/containers/install-cluster.sh
    permissions: '0744'
runcmd:
 -  [ /bin/bash, /opt/azure/containers/install-cluster.sh ]

